development:
  adapter: postgresql
  encoding: unicode
  database: hometeacher_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: hometeacher_test
  pool: 10

production:
  adapter: postgresql
  encoding: unicode
  database: hometeacher_production
  pool: 5
